UPDATE shows SET title = 'Adventure Time' WHERE title LIKE '_dventure _ime';
UPDATE shows SET title = 'Arrow' WHERE title LIKE '_rrow';
UPDATE shows SET title = 'Avatar: The Last Airbender' WHERE title LIKE '_vatar%';
UPDATE shows SET title = 'Brooklyn Nine-Nine' WHERE title LIKE '_rook%';
UPDATE shows SET title = 'Brooklyn Nine-Nine' WHERE title = 'B99';
UPDATE shows SET title = 'Community' WHERE title LIKE '%ommunity';
UPDATE shows SET title = 'Family Guy' WHERE title LIKE '%amily %uy';
UPDATE shows SET title = 'Friends' WHERE title LIKE '%riends';
UPDATE shows SET title = 'Game of Thrones' WHERE title LIKE '%ame %f %hrones';
UPDATE shows SET title = 'Game of Thrones' WHERE title LIKE 'G%O%T%';
UPDATE shows SET title = 'Gilmore Girls' WHERE title LIKE '%ilmore %irls';
UPDATE shows SET title = 'Grey’s Anatomy' WHERE title LIKE '%rey_s%';
UPDATE shows SET title = 'How I Met Your Mother' WHERE title LIKE '%ow % %et %our %other';
UPDATE shows SET title = 'It’s Always Sunny in Philadelphia' WHERE title LIKE '%lways _unny _n _hiladelphia';
UPDATE shows SET title = 'Parks and Recreation' WHERE title LIKE '_arks%_ec%';
UPDATE shows SET title = 'Sherlock' WHERE title LIKE '_herlock%';
UPDATE shows SET title = 'Squid Game' WHERE title LIKE '%quid _ame';
UPDATE shows SET title = 'The Bachelorette' WHERE title LIKE '%achelorette';
UPDATE shows SET title = 'The Crown' WHERE title LIKE '%rown';
UPDATE shows SET title = 'The Office' WHERE title LIKE '%ffice%';
UPDATE shows SET title = 'The Queen’s Gambit' WHERE title LIKE '%ueen’s _ambit';
UPDATE shows SET title = 'The Untamed' WHERE title LIKE '%ntamed';
UPDATE shows SET title = 'Billions' WHERE title = 'billions';
UPDATE shows SET title = 'Criminal Minds' WHERE title = 'criminal minds';
